version: "3.8"

services:
  app:
    build: .
    container_name: go_app
    restart: always
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=End291103#
      - DB_NAME=bwastartup
      - DB_PORT=3306
    networks:
      - app_network
    expose:
      - "8080"

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: End291103#
      MYSQL_DATABASE: bwastartup
    ports:
      - "3306:3306"
    networks:
      - app_network
    volumes:
      - mysql_data:/var/lib/mysql
      - ./bwastartup.sql:/docker-entrypoint-initdb.d/bwastartup.sql

  nginx:
    image: nginx:latest
    container_name: nginx_server
    restart: always
    depends_on:
      - app
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - app_network

networks:
  app_network:

volumes:
  mysql_data:
